import {StyleSheet} from 'react-native';
import {COLORS} from '../../constants/colors';

export const style = StyleSheet.create({
  title: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 20,
    color: COLORS.secondray,
  },
  top: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  date: {
    marginTop: 7,
    color: 'gray',
    fontSize: 13,
    lineHeight: 14,
    fontWeight: '400',
    width: '100%',
  },
  notes: {
    marginTop: 7,
    color: COLORS.secondray,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    width: '100%',
    zIndex: -1,
  },
  tags: {
    marginTop: 10,
    color: 'white',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '400',
    backgroundColor: COLORS.btn1,
    paddingVertical: 7,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: COLORS.light,
    width: 70,
    textAlign: 'center',
    marginBottom: 10,
  },
  tags1: {
    marginTop: 10,
    color: 'white',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '400',
    backgroundColor: COLORS.btn2,
    paddingVertical: 7,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: COLORS.light,
    width: 70,
    textAlign: 'center',
    marginBottom: 10,
  },
  pop: {
    backgroundColor: 'white',
    width: 105,
    position: 'absolute',
    top: 15,
    right: 20,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 15,
    elevation: 4,
    zIndex: 1,
  },
  edit: {
    color: COLORS.black,
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 18,
    textAlign: 'center',
  },
  delete: {
    color: COLORS.btn1,
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 18,
    textAlign: 'center',
  },
  hr: {
    backgroundColor: COLORS.light,
    height: 1,
    marginVertical: 3,
  },
  hide: {
    display: 'none',
  },
  tagBtn: {
    width: 70,
  },
});
