import {StyleSheet} from 'react-native';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingBottom: 30,
  },
  setting: {
    marginTop: 20,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    color: '#0B0A11',
    lineHeight: 24,
  },
  mainDiv: {
    marginTop: 25,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  name: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    gap: 10,
    alignItems: 'center',
    marginBottom: 10,
    width: '85%',
  },
  fullName: {
    fontSize: 16,
    fontWeight: '500',
    color: '#0B0A11',
    lineHeight: 24,
    width: '90%',
  },
  email: {
    fontSize: 12,
    fontWeight: '400',
    color: '#0B0A1166',
    lineHeight: 16,
    width: '90%',
  },
  about: {
    backgroundColor: '#F0F0F0',
    textAlign: 'center',
    paddingVertical: 10,
    color: '#0B0A1166',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    marginTop: 40,
  },
  changePassword: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 5,
    marginHorizontal: 10,
  },
  change: {
    color: '#0B0A11B2',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
  },
  hr: {
    height: 1,
    backgroundColor: '#F0F0F0',
    marginHorizontal: 15,
  },
  out: {
    color: '#BA1735',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    marginHorizontal: 15,
    marginTop: 20,
  },
  app: {
    textAlign: 'center',
    color: '#0B0A1133',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
  },
});
