import {StyleSheet} from 'react-native';
import {COLORS} from '../../constants/colors';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingBottom: 10,
    paddingHorizontal: 20,
  },
  mainDiv: {
    marginTop: 25,
  },
  subDiv: {
    marginTop: 10,
  },
  title: {
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    color: COLORS.secondray,
    marginBottom: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.light,
    paddingHorizontal: 10,
    borderRadius: 4,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 18,
    marginBottom: 10,
  },
  inputnotes: {
    borderWidth: 1,
    borderColor: COLORS.light,
    paddingHorizontal: 10,
    borderRadius: 4,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 18,
    marginBottom: 10,
    textAlignVertical: 'top',
    height: 120,
  },
  drop: {
    width: 100,
  },
  dropdownContainer: {
    borderWidth: 1,
    borderColor: COLORS.light,
    borderRadius: 4,
    padding: 10,
  },
  dropdownText: {
    fontSize: 14,
    fontWeight: '400',
    color: COLORS.black,
  },
  dropdownMenu: {
    borderWidth: 1,
    borderColor: COLORS.light,
    borderRadius: 4,
    marginTop: 5,
    backgroundColor: 'white',
    elevation: 2,
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  dropdownItem: {
    padding: 10,
    fontSize: 14,
    fontWeight: '400',
    color: COLORS.secondray,
  },
  remind: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
    color: COLORS.secondray,
    marginBottom: 8,
    marginTop: 12,
  },
  dateContainer: {
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: COLORS.light,
    borderRadius: 4,
    padding: 10,
  },
  dateLabel: {
    fontSize: 14,
    fontWeight: '400',
    color: COLORS.black,
  },
  datePicker: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 5,
  },
  dateText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.secondray,
    marginRight: 5,
    lineHeight: 22,
  },
  icon: {
    marginLeft: 10,
  },
  addTask: {
    backgroundColor: COLORS.primary,
    borderWidth: 1,
    borderColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 5,
    textAlign: 'center',
  },
  addText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 22,
    textAlign: 'center',
  },
  modelcontainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  line: {
    height: 3,
    borderRadius: 5,
    backgroundColor: COLORS.light,
    width: 35,
    marginHorizontal: 'auto',
    marginBottom: 10,
  },
  modelDiv: {
    backgroundColor: 'white',
    width: '100%',
    height: 'auto',
    paddingTop: 10,
    paddingBottom: 20,
    paddingHorizontal: 20,
    position: 'absolute',
    bottom: 0,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  titleModel: {
    fontSize: 18,
    fontWeight: '400',
    textAlign: 'center',
    lineHeight: 23,
    marginVertical: 10,
  },
  calendar: {
    borderRadius: 10,
    overflow: 'hidden',
  },
  selectedDate: {
    fontSize: 16,
    color: 'black',
    fontWeight: '700',
    textAlign: 'center',
    marginVertical: 15,
  },
  modelText: {
    fontSize: 20,
    fontWeight: '600',
    marginVertical: 20,
    textAlign: 'center',
    lineHeight: 24,
  },
});

export const calenderTheme = {
  backgroundColor: 'white',
  calendarBackground: 'white',
  selectedDayBackgroundColor: 'green',
  selectedDayTextColor: 'green',
  todayTextColor: 'green',
  dayTextColor: COLORS.black,
  textDisabledColor: COLORS.light,
  selectedDotColor: 'white',
  arrowColor: COLORS.black,
  monthTextColor: 'black',
  textMonthFontWeight: 'bold',
  textDayFontWeight: '300',
  textDayHeaderFontWeight: '300',
  textDayFontSize: 16,
  textMonthFontSize: 20,
  textDayHeaderFontSize: 14,
};
